### ISSUE TITLE
Building tests fails

### ISSUE THREAD

**Issue by tBuLi** [jeremyong/gal#2]
Hello @jeremyong,

Thanks for this awesome library! I'm looking forward to start writing some code with it! 

However, I'm trying to run the tests as indicated in the readme, but so far no success. Compiling one of the tests seems to fail on a clone I made today.

The steps I'm following:
```
# From the root directory of this project
mkdir build
cd build

# Optionally supply release type, flags, etc and pick your favorite generator
cmake .. -G Ninja

# ... or whichever (ideally multicore-friendly) build system you choose
ninja

# Run the tests
./bin/gal_test
```
Output from `cmake`:
```
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/u0114255/projects/GAUGE/gal/build
```
(Summary of) output from ninja:
```
In file included from ../public/gal/engine.hpp:4:0,
                 from ../public/gal/pga.hpp:3,
                 from ../test/test_dfa.cpp:3:
../public/gal/entity.hpp: In instantiation of ‘constexpr std::array<short int, sizeof... (N)> gal::detail::construct_element_lut(std::index_sequence<I ...>) [with unsigned char ...E = {}; long unsigned int ...N = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}; std::index_sequence<I ...> = std::integer_sequence<long unsigned int, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15>]’:
../public/gal/entity.hpp:64:46:   required from ‘constexpr const std::array<short int, 16> gal::entity<gal::algebra<gal::metric<3, 0, 1> >, float>::element_lut’
../public/gal/entity.hpp:91:60:   required from ‘constexpr auto gal::entity<A, T, E>::select() const [with unsigned char ...S = {1, 2, 4, 8}; A = gal::algebra<gal::metric<3, 0, 1> >; T = float; unsigned char ...E = {}]’
../public/gal/pga.hpp:369:66:   required from ‘constexpr gal::pga::plane<T>::plane(gal::entity<gal::algebra<gal::metric<3, 0, 1> >, T, E ...>) [with unsigned char ...E = {}; T = float]’
../test/test_dfa.cpp:157:72:   required from here
../public/gal/entity.hpp:49:36: error: no matching function for call to ‘indexof<0, 0>()’
         return {indexof<N, 0, E...>()...};
                 ~~~~~~~~~~~~~~~~~~~^~
../public/gal/entity.hpp:29:37: note: candidate: template<unsigned char E, short int I, unsigned char E1, unsigned char ...Es> constexpr int16_t gal::detail::indexof()
     GAL_NODISCARD constexpr int16_t indexof() noexcept
                                     ^~~~~~~
../public/gal/entity.hpp:29:37: note:   template argument deduction/substitution failed:
../public/gal/entity.hpp:49:36: note:   couldn't deduce template parameter ‘E1’
         return {indexof<N, 0, E...>()...};
                 ~~~~~~~~~~~~~~~~~~~^~
../public/gal/entity.hpp:49:41: error: could not convert ‘{<expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘std::array<short int, 16>’
         return {indexof<N, 0, E...>()...};
                                         ^
../public/gal/entity.hpp: In instantiation of ‘constexpr const std::array<short int, 16> gal::entity<gal::algebra<gal::metric<3, 0, 1> >, float>::element_lut’:
../public/gal/entity.hpp:91:60:   required from ‘constexpr auto gal::entity<A, T, E>::select() const [with unsigned char ...S = {1, 2, 4, 8}; A = gal::algebra<gal::metric<3, 0, 1> >; T = float; unsigned char ...E = {}]’
../public/gal/pga.hpp:369:66:   required from ‘constexpr gal::pga::plane<T>::plane(gal::entity<gal::algebra<gal::metric<3, 0, 1> >, T, E ...>) [with unsigned char ...E = {}; T = float]’
../test/test_dfa.cpp:157:72:   required from here
../public/gal/entity.hpp:64:46:   in constexpr expansion of ‘gal::detail::construct_element_lut<, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15>((std::make_index_sequence<16>{}, std::make_index_sequence<16>()))’
../public/gal/entity.hpp:63:81: error: constexpr call flows off the end of the function
     constexpr static std::array<int16_t, (1 << algebra_t::metric_t::dimension)> element_lut
                                                                                 ^~~~~~~~~~~
[7/8] Building CXX object test/CMakeFiles/gal_test.dir/test.cpp.o
ninja: build stopped: subcommand failed.
```
Versions I'm using:
cmake 3.15.5
ninja 1.8.2
gcc 7.4.0

Can you help me understand whether I did something wrong or if this is a (new) issue?

**Comment by jeremyong** [comment]
Hey! I think your gcc version is a bit behind. GAL relies on a number of pretty heavy duty C++17 tricks to get fast compilation time, and unfortunately, older compiler versions (even ones that claim C++17 support) have issues and were not 100% conformant. Can you try a more recent gcc and report back?

**Comment by jeremyong** [comment]
Also, thanks for taking interest in the library :) It's still a WIP as you can tell, but I'd love to hear about what you hope to do with it and what your use case is. On my todo list, there are still a number of things I need to check off before I'd be comfortable "releasing" it with an official stable release.

**Comment by tBuLi** [comment]
Thank you for your quick reply! I should've remembered that actually, @enkimute told me that this library was being developed right on the cutting edge. I upgraded to gcc 9.2.1 and now all the tests succeeded! (A bit annoying that gcc 7 claims C++17 since I double checked that before starting.)

**Comment by tBuLi** [comment]
I'm doing lattice QCD, so my usecase is **large** numbers of SU(N) elements :). Since this library seems to be very powerful, it seems like a good place to start! Any suggestions you might have for me on how to generate general R^N algebra's would be welcome btw, although I'll start reading the source now. I'm particularly interested in R^6.

**Comment by jeremyong** [comment]
Hehe ok, a good file to start looking at is [pga.hpp](https://github.com/jeremyong/gal/blob/master/public/gal/pga.hpp). At the top, you'll see how a `metric` and `algebra` are defined followed by literals that can be used like `1_e12` for example. Later, in this case, you'd include `using namespace gal::pga` so that the file uses pga (substitute for 600). The file itself is optional for working with the library but defines convenient entities like a "point" representation. You don't need to create these entities if you don't want. Using `auto` return type deduction gives you a templated `entity` type (see [here](https://github.com/jeremyong/gal/blob/master/public/gal/entity.hpp#L58). You can then use `operator[N]` to index the nth element of the returned result. If you need to select a particular coefficient of the multivector, use `result.select(e)` where `e` is the element in question.

For example, `auto result = compute([](auto ...) { ... }, ...; return result.select(0b110);` returns the value in the `e_12` component of the result of that computation.

Documentation is unfortunately sparse right now (the library API isn't 100% stable) so apologies for that in advance.

I don't foresee any issues defining the R600 metric, but let me know if you encounter any problems. Be advised that "late-stage CSE" is something that's still on my [todo list](https://github.com/jeremyong/gal/projects/1) so maybe if there was one concern, it's that computation still isn't 100% as fast as I would like (but still pretty competitive with alternatives).

**Comment by tBuLi** [comment]
Excellent, thanks for your quick reply! I'll just start playing around with it a bit and let you know if I run into problems. With those pointers I have enough information to get started, thanks. The "not as fast as possible" performance wont be an issue for me during my playing around :P.
